//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.235.
// 
#pragma warning disable 1591

namespace SPKTWeb.DkmhWebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsrSerSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedEnd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuralObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityKeyMember[]))]
    public partial class UsrSer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUserByUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRolesByUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserProfileByUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsStudentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentByUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUserExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UsrSer() {
            this.Url = global::SPKTWeb.Properties.Settings.Default.SPKTWeb_DkmhWebservice_UsrSer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUserByUserNameCompletedEventHandler GetUserByUserNameCompleted;
        
        /// <remarks/>
        public event GetRolesByUserNameCompletedEventHandler GetRolesByUserNameCompleted;
        
        /// <remarks/>
        public event GetUserProfileByUserNameCompletedEventHandler GetUserProfileByUserNameCompleted;
        
        /// <remarks/>
        public event IsStudentCompletedEventHandler IsStudentCompleted;
        
        /// <remarks/>
        public event GetStudentByUserNameCompletedEventHandler GetStudentByUserNameCompleted;
        
        /// <remarks/>
        public event IsUserExistCompletedEventHandler IsUserExistCompleted;
        
        /// <remarks/>
        public event ValidateUserCompletedEventHandler ValidateUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserByUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public users GetUserByUserName(string username) {
            object[] results = this.Invoke("GetUserByUserName", new object[] {
                        username});
            return ((users)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByUserNameAsync(string username) {
            this.GetUserByUserNameAsync(username, null);
        }
        
        /// <remarks/>
        public void GetUserByUserNameAsync(string username, object userState) {
            if ((this.GetUserByUserNameOperationCompleted == null)) {
                this.GetUserByUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByUserNameOperationCompleted);
            }
            this.InvokeAsync("GetUserByUserName", new object[] {
                        username}, this.GetUserByUserNameOperationCompleted, userState);
        }
        
        private void OnGetUserByUserNameOperationCompleted(object arg) {
            if ((this.GetUserByUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByUserNameCompleted(this, new GetUserByUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRolesByUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetRolesByUserName(string username) {
            object[] results = this.Invoke("GetRolesByUserName", new object[] {
                        username});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRolesByUserNameAsync(string username) {
            this.GetRolesByUserNameAsync(username, null);
        }
        
        /// <remarks/>
        public void GetRolesByUserNameAsync(string username, object userState) {
            if ((this.GetRolesByUserNameOperationCompleted == null)) {
                this.GetRolesByUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRolesByUserNameOperationCompleted);
            }
            this.InvokeAsync("GetRolesByUserName", new object[] {
                        username}, this.GetRolesByUserNameOperationCompleted, userState);
        }
        
        private void OnGetRolesByUserNameOperationCompleted(object arg) {
            if ((this.GetRolesByUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRolesByUserNameCompleted(this, new GetRolesByUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserProfileByUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public profiles GetUserProfileByUserName(string username) {
            object[] results = this.Invoke("GetUserProfileByUserName", new object[] {
                        username});
            return ((profiles)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserProfileByUserNameAsync(string username) {
            this.GetUserProfileByUserNameAsync(username, null);
        }
        
        /// <remarks/>
        public void GetUserProfileByUserNameAsync(string username, object userState) {
            if ((this.GetUserProfileByUserNameOperationCompleted == null)) {
                this.GetUserProfileByUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserProfileByUserNameOperationCompleted);
            }
            this.InvokeAsync("GetUserProfileByUserName", new object[] {
                        username}, this.GetUserProfileByUserNameOperationCompleted, userState);
        }
        
        private void OnGetUserProfileByUserNameOperationCompleted(object arg) {
            if ((this.GetUserProfileByUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserProfileByUserNameCompleted(this, new GetUserProfileByUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsStudent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsStudent(string username) {
            object[] results = this.Invoke("IsStudent", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsStudentAsync(string username) {
            this.IsStudentAsync(username, null);
        }
        
        /// <remarks/>
        public void IsStudentAsync(string username, object userState) {
            if ((this.IsStudentOperationCompleted == null)) {
                this.IsStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsStudentOperationCompleted);
            }
            this.InvokeAsync("IsStudent", new object[] {
                        username}, this.IsStudentOperationCompleted, userState);
        }
        
        private void OnIsStudentOperationCompleted(object arg) {
            if ((this.IsStudentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsStudentCompleted(this, new IsStudentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStudentByUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sinhvien GetStudentByUserName(string username) {
            object[] results = this.Invoke("GetStudentByUserName", new object[] {
                        username});
            return ((sinhvien)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentByUserNameAsync(string username) {
            this.GetStudentByUserNameAsync(username, null);
        }
        
        /// <remarks/>
        public void GetStudentByUserNameAsync(string username, object userState) {
            if ((this.GetStudentByUserNameOperationCompleted == null)) {
                this.GetStudentByUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentByUserNameOperationCompleted);
            }
            this.InvokeAsync("GetStudentByUserName", new object[] {
                        username}, this.GetStudentByUserNameOperationCompleted, userState);
        }
        
        private void OnGetStudentByUserNameOperationCompleted(object arg) {
            if ((this.GetStudentByUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentByUserNameCompleted(this, new GetStudentByUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsUserExist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsUserExist(string username) {
            object[] results = this.Invoke("IsUserExist", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUserExistAsync(string username) {
            this.IsUserExistAsync(username, null);
        }
        
        /// <remarks/>
        public void IsUserExistAsync(string username, object userState) {
            if ((this.IsUserExistOperationCompleted == null)) {
                this.IsUserExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUserExistOperationCompleted);
            }
            this.InvokeAsync("IsUserExist", new object[] {
                        username}, this.IsUserExistOperationCompleted, userState);
        }
        
        private void OnIsUserExistOperationCompleted(object arg) {
            if ((this.IsUserExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUserExistCompleted(this, new IsUserExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidateUser(string username, string password) {
            object[] results = this.Invoke("ValidateUser", new object[] {
                        username,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string username, string password) {
            this.ValidateUserAsync(username, password, null);
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string username, string password, object userState) {
            if ((this.ValidateUserOperationCompleted == null)) {
                this.ValidateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserOperationCompleted);
            }
            this.InvokeAsync("ValidateUser", new object[] {
                        username,
                        password}, this.ValidateUserOperationCompleted, userState);
        }
        
        private void OnValidateUserOperationCompleted(object arg) {
            if ((this.ValidateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserCompleted(this, new ValidateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class users : EntityObject {
        
        private string usernameField;
        
        private string emailField;
        
        private string commentField;
        
        private string passwordField;
        
        private System.Nullable<byte> isApprovedField;
        
        private System.Nullable<System.DateTime> lastLoginDateField;
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private System.Nullable<byte> isLockedOutField;
        
        private System.Nullable<System.DateTime> lastLockedOutDateField;
        
        private System.Nullable<int> failedPasswordAttemptCountField;
        
        private System.Nullable<System.DateTime> failedPasswordAttemptWindowStartField;
        
        private string verificationCodeField;
        
        private System.Nullable<System.DateTime> validTimeOutField;
        
        private EntityReferenceOfprofiles profilesReferenceField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> IsApproved {
            get {
                return this.isApprovedField;
            }
            set {
                this.isApprovedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastLoginDate {
            get {
                return this.lastLoginDateField;
            }
            set {
                this.lastLoginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> IsLockedOut {
            get {
                return this.isLockedOutField;
            }
            set {
                this.isLockedOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastLockedOutDate {
            get {
                return this.lastLockedOutDateField;
            }
            set {
                this.lastLockedOutDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FailedPasswordAttemptCount {
            get {
                return this.failedPasswordAttemptCountField;
            }
            set {
                this.failedPasswordAttemptCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FailedPasswordAttemptWindowStart {
            get {
                return this.failedPasswordAttemptWindowStartField;
            }
            set {
                this.failedPasswordAttemptWindowStartField = value;
            }
        }
        
        /// <remarks/>
        public string VerificationCode {
            get {
                return this.verificationCodeField;
            }
            set {
                this.verificationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ValidTimeOut {
            get {
                return this.validTimeOutField;
            }
            set {
                this.validTimeOutField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfprofiles profilesReference {
            get {
                return this.profilesReferenceField;
            }
            set {
                this.profilesReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfprofiles : EntityReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfusers))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfprofiles))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityReference : RelatedEnd {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
            }
        }
        
        /// <remarks/>
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
            }
        }
        
        /// <remarks/>
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfusers))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfprofiles))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class RelatedEnd {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sinhvien))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(profiles))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(users))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sinhvien))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(profiles))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(users))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class sinhvien : EntityObject {
        
        private string maSinhVienField;
        
        private string hoField;
        
        private string tenField;
        
        private System.Nullable<byte> phaiField;
        
        private System.Nullable<System.DateTime> ngaySinh_OriField;
        
        private string noiSinhField;
        
        private string chuyenNganhField;
        
        private string lopField;
        
        private string ngaySinhField;
        
        /// <remarks/>
        public string MaSinhVien {
            get {
                return this.maSinhVienField;
            }
            set {
                this.maSinhVienField = value;
            }
        }
        
        /// <remarks/>
        public string Ho {
            get {
                return this.hoField;
            }
            set {
                this.hoField = value;
            }
        }
        
        /// <remarks/>
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> Phai {
            get {
                return this.phaiField;
            }
            set {
                this.phaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> NgaySinh_Ori {
            get {
                return this.ngaySinh_OriField;
            }
            set {
                this.ngaySinh_OriField = value;
            }
        }
        
        /// <remarks/>
        public string NoiSinh {
            get {
                return this.noiSinhField;
            }
            set {
                this.noiSinhField = value;
            }
        }
        
        /// <remarks/>
        public string ChuyenNganh {
            get {
                return this.chuyenNganhField;
            }
            set {
                this.chuyenNganhField = value;
            }
        }
        
        /// <remarks/>
        public string Lop {
            get {
                return this.lopField;
            }
            set {
                this.lopField = value;
            }
        }
        
        /// <remarks/>
        public string NgaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                this.ngaySinhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class profiles : EntityObject {
        
        private string usernameField;
        
        private System.Nullable<System.DateTime> lastUpdatedDateField;
        
        private string propertyNamesField;
        
        private string propertyValuesStringField;
        
        private EntityReferenceOfusers usersReferenceField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastUpdatedDate {
            get {
                return this.lastUpdatedDateField;
            }
            set {
                this.lastUpdatedDateField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyNames {
            get {
                return this.propertyNamesField;
            }
            set {
                this.propertyNamesField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyValuesString {
            get {
                return this.propertyValuesStringField;
            }
            set {
                this.propertyValuesStringField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfusers usersReference {
            get {
                return this.usersReferenceField;
            }
            set {
                this.usersReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfusers : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUserByUserNameCompletedEventHandler(object sender, GetUserByUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public users Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((users)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRolesByUserNameCompletedEventHandler(object sender, GetRolesByUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRolesByUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRolesByUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUserProfileByUserNameCompletedEventHandler(object sender, GetUserProfileByUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserProfileByUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserProfileByUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public profiles Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((profiles)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsStudentCompletedEventHandler(object sender, IsStudentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetStudentByUserNameCompletedEventHandler(object sender, GetStudentByUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentByUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentByUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sinhvien Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sinhvien)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsUserExistCompletedEventHandler(object sender, IsUserExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUserExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUserExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ValidateUserCompletedEventHandler(object sender, ValidateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591