<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="SPKTWeb.WebForm1" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:GridView ID="GridView1" runat="server" AllowSorting="True" 
            AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="CategoryID" 
            DataSourceID="ObjectDataSource1">
            <Columns>
                <asp:BoundField DataField="CategoryID" HeaderText="CategoryID" 
                    SortExpression="CategoryID" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Subject" HeaderText="Subject" 
                    SortExpression="Subject" />
                <asp:BoundField DataField="SortOrder" HeaderText="SortOrder" 
                    SortExpression="SortOrder" />
                <asp:BoundField DataField="CreateDate" HeaderText="CreateDate" 
                    SortExpression="CreateDate" />
                <asp:BoundField DataField="UpdateDate" HeaderText="UpdateDate" 
                    SortExpression="UpdateDate" />
                <asp:BoundField DataField="ThreadCount" HeaderText="ThreadCount" 
                    SortExpression="ThreadCount" />
                <asp:BoundField DataField="PostCount" HeaderText="PostCount" 
                    SortExpression="PostCount" />
                <asp:BoundField DataField="LastPostDate" HeaderText="LastPostDate" 
                    SortExpression="LastPostDate" />
                <asp:BoundField DataField="LastPostByAccountID" 
                    HeaderText="LastPostByAccountID" SortExpression="LastPostByAccountID" />
                <asp:BoundField DataField="LastPostByUsername" HeaderText="LastPostByUsername" 
                    SortExpression="LastPostByUsername" />
                <asp:BoundField DataField="PageName" HeaderText="PageName" 
                    SortExpression="PageName" />
                
            </Columns>
        </asp:GridView>
        <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" 
            DataObjectTypeName="SPKTCore.Core.Domain.BoardCategory" 
            DeleteMethod="DeleteCategory" SelectMethod="GetAllCategories" 
            TypeName="SPKTCore.Core.DataAccess.Impl.BoardCategoryRepository" 
            UpdateMethod="SaveCategory"></asp:ObjectDataSource>
    
        <br />
        <br />
        <asp:Button ID="Button1" runat="server" onclick="Button1_Click" Text="Button" />
        <br />
    
    </div>
    </form>
</body>
</html>
