//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPKTWeb.Forums {
    
    
    public partial class ViewForum1 {
        
        /// <summary>
        /// UCForumHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SPKTWeb.Forums.UserControl.ForumHeader UCForumHeader;
        
        /// <summary>
        /// UCViewAllPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SPKTWeb.Forums.UserControl.ViewAllPost UCViewAllPost;
        
        /// <summary>
        /// UCViewTopPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SPKTWeb.Forums.UserControl.ViewTopPost UCViewTopPost;
        
        /// <summary>
        /// UCViewTopPost1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SPKTWeb.Forums.UserControl.ViewTopPost UCViewTopPost1;
    }
}
